Update models.py
I can't migrate error showing 
SystemCheckError: System check identified some issues:
ERRORS:
oidc_provider.Code.user: (fields.E303) Reverse query name for 'Code.user' clashes with field name 'Account.code'.
	HINT: Rename field 'Account.code', or add/change a related_name argument to the definition for field 'Code.user'.
oidc_provider.Token.user: (fields.E303) Reverse query name for 'Token.user' clashes with field name 'Account.token'.
	HINT: Rename field 'Account.token', or add/change a related_name argument to the definition for field 'Token.user'.